version: 2

env:
  - GO111MODULE=on

before:
  hooks:
    - go mod download

builds:
  -
    main: ./main.go
    binary: tt
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64
      - goos: linux
        goarch: arm64

archives:
  - format_overrides:
      - goos: windows
        format: "zip"
    files:
      - LICENSE.txt
      - README.md
      - tt.toml.example

release:
  prerelease: auto

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
